# Generated by Django 3.2.9 on 2021-11-15 15:21

import classes.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0004_auto_20211109_1659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('video', models.FileField(null=True, upload_to=classes.models.media_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active_students', models.ManyToManyField(related_name='active_classes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='classes', to='categories.subcategory')),
                ('students_history', models.ManyToManyField(related_name='classes_paid', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'unique_together': {('teacher', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ClassRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Awful'), (25, 'Bad'), (50, 'Average'), (75, 'Good'), (100, 'Amazing')])),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(limit_choices_to={'is_teacher': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('rated_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='classes.class')),
            ],
        ),
        migrations.CreateModel(
            name='classImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=25, null=True, upload_to=classes.models.media_upload_path)),
                ('of_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='classes.class')),
            ],
        ),
    ]
