# Generated by Django 3.2.9 on 2021-11-15 16:18

import classes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='active_students',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='students_history',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes_paid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=classes.models.media_upload_path),
        ),
    ]
