# Generated by Django 3.2.9 on 2021-11-15 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0002_auto_20211115_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='active_students',
            field=models.ManyToManyField(blank=True, related_name='active_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='students_history',
            field=models.ManyToManyField(blank=True, related_name='classes_paid', to=settings.AUTH_USER_MODEL),
        ),
    ]
