# Generated by Django 3.2.9 on 2021-11-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_auto_20211115_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
