# Generated by Django 3.2.9 on 2021-11-17 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0004_alter_classrating_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='active_students',
        ),
        migrations.RemoveField(
            model_name='class',
            name='price',
        ),
        migrations.RemoveField(
            model_name='class',
            name='students_history',
        ),
        migrations.AddField(
            model_name='class',
            name='basic_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_duration', models.PositiveSmallIntegerField()),
                ('appointed_time', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('price_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='classes.class')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
