# Generated by Django 3.2.9 on 2021-11-09 16:08

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20211109_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=categories.models.category_thumbnail_path),
        ),
    ]
